[file]

[backends]
    [backends.freenas]
        [backends.freenas.servers.freenas]
            url = "http://192.168.20.10"
    [backends.plex]
        [backends.plex.servers.plex]
            url = "http://192.168.20.20:32400"
    [backends.prox]
        [backends.prox.servers.prox]
            url = "https://192.168.20.55:8006"

[frontends]
    [frontends.freenas]
        backend = "freenas"
        passHostHeader = true
        SSLRedirect=true
        [frontends.freenas.auth.forward]
        address = "http://oauth:4181"
        authResponseHeaders = ["X-Forwarded-User"]
        [frontends.freenas.routes.domain]
            rule = "Host:freenas.murac.com"
    [frontends.prox]
        backend = "prox"
        passHostHeader = true
        SSLRedirect=true
        [frontends.prox.auth.forward]
        address = "http://oauth:4181"
        authResponseHeaders = ["X-Forwarded-User"]
        [frontends.prox.routes.domain]
            rule = "Host:prox.murac.com"
    [frontends.plex]
        backend = "plex"
        passHostHeader = true
        SSLRedirect=true
        # [frontends.plex.auth.forward]
        # address = "http://oauth:4181"
        # authResponseHeaders = ["X-Forwarded-User"]
        [frontends.plex.routes.domain]
            rule = "Host:plex.murac.com"